#!/bin/bash

amend=false
gem_names=()

set -e
for arg in $@
do
  if [ "${arg}" == "--amend" ]; then
    amend=true
  else
    gem_names+=($arg)
  fi
done
if [ "${amend}" == "false" ]; then
  shift
  commit_args='--amend -C head'
else
  commit_args="-m \"update $gem_names\""
fi

set -x
# bundle update $gem_names && bundle exec rake && 
git commit -a $commit_args
